### ISSUE TITLE
Use ^ for mantine deps

### ISSUE THREAD

**Issue by elibroftw** [mantinedev/mantine-vite-template#3]
https://github.com/mantinedev/mantine-vite-template/blob/master/package.json#L19

Otherwise when adding a library like mantine hooks, we have to do it ourselves.

**Comment by rtivital** [comment]
All mantine packages must have the same version, for example `@mantine/core@5.10.0` maybe incompatible with `@mantine/hooks@5.9.0`. It is recommended to use versions without any modifiers in package.json.
